import {
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { afterEach, beforeEach, expect, it } from 'vitest';

const cli = fileURLToPath(
  new URL('../packages/cli/dist/index.js', import.meta.url),
);
const chart = (title: string, value = '18') =>
  `\`\`\`chart\ntype: bar\ntitle: ${title}\n\n| Package | Size |\n| --- | ---: |\n| Core | ${value} |\n\`\`\``;
const source =
  '# Benchmarks\n\n' + chart('Bundle size') + '\n\n' + chart('Runtime');
let cwd: string;
let output: string;
beforeEach(() => {
  cwd = mkdtempSync(join(tmpdir(), 'chartmd-build-'));
  output = join(cwd, '.github/charts');
  writeFileSync(join(cwd, 'README.md'), source);
});
afterEach(() => {
  rmSync(cwd, { recursive: true, force: true });
});
const run = (...args: string[]) =>
  spawnSync(process.execPath, [cli, ...args], { cwd, encoding: 'utf8' });

it('builds all README charts into the default directory without modifying Markdown', () => {
  const result = run('build', 'README.md');
  expect(result.status).toBe(0);
  expect(result.stdout).toContain('Built 2 charts');
  expect(readdirSync(output).sort()).toEqual([
    'bundle-size.svg',
    'runtime.svg',
  ]);
  expect(readFileSync(join(output, 'bundle-size.svg'), 'utf8')).toContain(
    'Bundle size</title>',
  );
  expect(readFileSync(join(cwd, 'README.md'), 'utf8')).toBe(source);
});
it('creates nested custom output directories relative to cwd, including spaces', () => {
  mkdirSync(join(cwd, 'docs'));
  writeFileSync(join(cwd, 'docs/benchmarks.md'), source);
  expect(
    run('build', 'docs/benchmarks.md', '--output', 'assets/my charts').status,
  ).toBe(0);
  expect(existsSync(join(cwd, 'assets/my charts/runtime.svg'))).toBe(true);
  expect(existsSync(output)).toBe(false);
});
it('rebuilds changed SVGs, preserves unchanged file mtimes, and leaves old charts alone', () => {
  expect(run('build', 'README.md').status).toBe(0);
  const runtime = join(output, 'runtime.svg');
  const original = readFileSync(runtime, 'utf8');
  const mtime = statSync(runtime).mtimeMs;
  writeFileSync(
    join(cwd, 'README.md'),
    source.replace('Core | 18', 'Core | 29'),
  );
  expect(run('build', 'README.md').status).toBe(0);
  expect(readFileSync(join(output, 'bundle-size.svg'), 'utf8')).toContain('29');
  expect(readFileSync(runtime, 'utf8')).toBe(original);
  expect(statSync(runtime).mtimeMs).toBe(mtime);
  writeFileSync(join(cwd, 'README.md'), chart('Bundle size'));
  expect(run('build', 'README.md').status).toBe(0);
  expect(existsSync(runtime)).toBe(true);
});
it('reports no charts without creating directories', () => {
  writeFileSync(join(cwd, 'README.md'), '# Nothing here');
  const result = run('build', 'README.md');
  expect(result.status).toBe(0);
  expect(result.stdout).toContain('No chart blocks');
  expect(existsSync(output)).toBe(false);
});
it('validates the whole document before writing and includes the source filename', () => {
  writeFileSync(
    join(cwd, 'README.md'),
    chart('First') + '\n\n' + chart('Second', 'bad'),
  );
  const result = run('build', 'README.md');
  expect(result.status).toBe(1);
  expect(result.stderr).toContain('README.md: Line 16:');
  expect(existsSync(output)).toBe(false);
});
it('rejects duplicate IDs before updating existing generated files', () => {
  expect(run('build', 'README.md').status).toBe(0);
  const original = readFileSync(join(output, 'bundle-size.svg'), 'utf8');
  writeFileSync(
    join(cwd, 'README.md'),
    chart('Bundle size', '99') + '\n' + chart('Bundle size'),
  );
  expect(run('build', 'README.md').stderr).toContain('duplicate chart ID');
  expect(readFileSync(join(output, 'bundle-size.svg'), 'utf8')).toBe(original);
});
it('checks all existing destinations before writing and preserves unrelated files', () => {
  mkdirSync(output, { recursive: true });
  writeFileSync(join(output, 'runtime.svg'), 'handwritten SVG');
  const result = run('build', 'README.md');
  expect(result.status).toBe(1);
  expect(result.stderr).toContain('not generated by chartmd');
  expect(existsSync(join(output, 'bundle-size.svg'))).toBe(false);
  expect(readFileSync(join(output, 'runtime.svg'), 'utf8')).toBe(
    'handwritten SVG',
  );
});
it('refuses symlink destinations and preserves the target', () => {
  mkdirSync(output, { recursive: true });
  symlinkSync(join(cwd, 'README.md'), join(output, 'bundle-size.svg'));
  expect(run('build', 'README.md').stderr).toContain('non-regular file');
  expect(lstatSync(join(output, 'bundle-size.svg')).isSymbolicLink()).toBe(
    true,
  );
  expect(readFileSync(join(cwd, 'README.md'), 'utf8')).toBe(source);
});
it.each([
  ['build'],
  ['build', 'missing.md'],
  ['build', 'README.md', '--output'],
  ['build', 'README.md', '--unknown', 'x'],
  ['build', 'README.md', 'another.md'],
])('reports invalid invocation %j', (...args) => {
  const result = run(...args);
  expect(result.status).toBe(1);
  expect(result.stderr).toContain('chartmd:');
  expect(result.stderr).not.toContain('at main');
  expect(existsSync(output)).toBe(false);
});

it('preserves the input even when an output directory alias resolves to it', () => {
  const marked =
    '<!-- Generated by chartmd build. -->\n' + chart('Bundle size');
  writeFileSync(join(cwd, 'bundle-size.svg'), marked);
  symlinkSync(cwd, join(cwd, 'alias'), 'dir');
  const result = run('build', 'bundle-size.svg', '--output', 'alias');
  expect(result.status).toBe(1);
  expect(result.stderr).toContain('different files');
  expect(readFileSync(join(cwd, 'bundle-size.svg'), 'utf8')).toBe(marked);
});
it('reports output directory failures without leaving temporary files', () => {
  writeFileSync(join(cwd, 'blocked'), 'file');
  expect(run('build', 'README.md', '--output', 'blocked/charts').status).toBe(
    1,
  );
  expect(readFileSync(join(cwd, 'blocked'), 'utf8')).toBe('file');
  expect(readdirSync(cwd).some((name) => name.endsWith('.tmp'))).toBe(false);
});

it.each([
  ['../README.md', '../.github/charts/'],
  ['../examples/readme/README.md', '../examples/readme/charts/'],
])('keeps the committed demo SVGs reproducible from %s', (markdown, charts) => {
  const input = fileURLToPath(new URL(markdown, import.meta.url));
  const expected = fileURLToPath(new URL(charts, import.meta.url));
  const destination = join(cwd, 'demo');
  expect(run('build', input, '--output', destination).status).toBe(0);
  expect(readdirSync(destination).sort()).toEqual(readdirSync(expected).sort());
  for (const name of readdirSync(expected)) {
    expect(readFileSync(join(destination, name), 'utf8')).toBe(
      readFileSync(join(expected, name), 'utf8'),
    );
  }
});
