import {
  lstat,
  mkdir,
  readFile,
  realpath,
  rename,
  rm,
  writeFile,
} from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import { ChartError, parseDocument, render } from '@chartmd/core';

const marker = '<!-- Generated by chartmd build. -->\n';

export async function build(
  input: string,
  source: string,
  output: string,
): Promise<void> {
  const charts = parseDocument(source);
  if (!charts.length) {
    console.log(`No chart blocks found in ${input}`);
    return;
  }
  // Render and check every destination before making any filesystem changes.
  const files = charts.map(({ id, chart }) => ({
    path: join(output, `${id}.svg`),
    content: marker + render(chart),
    unchanged: false,
  }));
  const realInput = await realpath(input);
  for (const file of files) {
    if (resolve(file.path) === input)
      throw new ChartError('Input and output must be different files.');
    let info;
    try {
      info = await lstat(file.path);
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
    }
    if (!info) continue;
    if (!info.isFile())
      throw new ChartError(
        `Refusing to replace non-regular file: ${file.path}`,
      );
    if ((await realpath(file.path)) === realInput)
      throw new ChartError('Input and output must be different files.');
    const current = await readFile(file.path, 'utf8');
    if (!current.startsWith(marker))
      throw new ChartError(
        `Refusing to overwrite a file not generated by chartmd build: ${file.path}`,
      );
    file.unchanged = current === file.content;
  }
  await mkdir(output, { recursive: true });
  for (const file of files) {
    if (file.unchanged) continue;
    const temporary = join(output, `.chartmd-${randomUUID()}.tmp`);
    try {
      await writeFile(temporary, file.content, { flag: 'wx' });
      await rename(temporary, file.path);
    } finally {
      await rm(temporary, { force: true });
    }
  }
  console.log(
    `Built ${files.length} chart${files.length === 1 ? '' : 's'} in ${output}`,
  );
}
